image:
  file: .gitpod.Dockerfile

tasks:
  - name: start cpu stress
    command: stress-ng --cpu 3 --backoff 10000000 --timeout 600s 
  - name: start io stress
    command: fio --name io-stress --eta-newline=5s --filename=/workspace/gitpod.temp --rw=randrw --size=2g --io_size=50g --blocksize=8k --ioengine=libaio --fsync=1000 --iodepth=10 --direct=1 --numjobs=20 --runtime=600
  - name: start memory stress
    command: stress-ng --vm 1 --vm-keep --vm-bytes 6G

